# trigger:
# - main

# pr:
# - '*'

# pool:
#   vmImage: 'ubuntu-latest'

# jobs:
# - job: DeployToDev
#   displayName: 'Deploy to Dev Environment'
#   steps:
#   - task: NodeTool@0
#     inputs:
#       versionSpec: '14.x'
#     displayName: 'Install Node.js'
  
#   - script: |
#       npm install -g serverless
#       npm install
      
#     displayName: 'Install Serverless Framework and Dependencies'
 
#   - task: AzureCLI@1
#     inputs:
#       azureSubscription: 'conn_for_serverless'
     
#       scriptLocation: 'inlineScript'
#       inlineScript: |
#         cd myservice
#         npm install
#         sls deploy
#       addSpnToEnvironment: true

trigger:
- main
pr:
- '*'
pool:
  vmImage: 'ubuntu-latest'
jobs:
- job: DeployToDev
  displayName: 'Deploy to Dev Environment'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'
  - script: |
      npm install -g serverless
      npm install
    displayName: 'Install Serverless Framework and Dependencies'
  - task: AzureCLI@0
    inputs:
     connectedServiceName: # string. Required when connectedServiceNameSelector = connectedServiceName. Azure Classic Subscription. 
     scriptLocation: 'scriptPath' # 'inlineScript' | 'scriptPath'. Required. Script Location. Default: scriptPath.
     scriptPath: # string. Required when scriptLocation = scriptPath. Script Path. 
     inlineScript: |
      cd myservice 
      npm install 
      serverless deploy

# trigger:z
# - main

# pool:
#   vmImage: 'ubuntu-latest'

# jobs:
# - job: DeployServerlessApp
#   steps:
#   - checkout: self

#   - task: UsePythonVersion@0
#     inputs:
#       versionSpec: '3.x'
#       addToPath: true

#   - script: |
#       npm install -g serverless
#     displayName: 'Install Serverless Framework'

#   - script: |
#       npm install
#     displayName: 'Install Node.js Dependencies'

#   - script: |
#       # Replace with your actual Serverless Framework commands
      
#     displayName: 'Deploy Serverless Application'
  


