trigger:
- main

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DeployToDev
  displayName: 'Deploy to Dev Environment'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'
  
  - script: |
      npm install -g serverless
      npm install
    displayName: 'Install Serverless Framework and Dependencies'

  - script: |
      npm install
      cd myservice
      ls
      npm install 
      serverless deploy
      
    displayName: 'Deploy Serverless Application to Dev Environment'
