trigger:
- main

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DeployToDev
  displayName: 'Deploy to Dev Environment'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'
  
  - script: |
      npm install -g serverless
      npm install
      
    displayName: 'Install Serverless Framework and Dependencies'
 
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'conn_for_serverless'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        sudo cd myservice
        sudo npm install
        sudo serverless deploy
      addSpnToEnvironment: true


